### ISSUE TITLE
Missing feature documentation

### ISSUE THREAD

**Issue by nicolas-f** [orbisgis/doc.orbisgis.org#22]
In the page:
http://orbisgis.readthedocs.io/en/latest/users/sql_console.html#sql-console

There is no information about the timeout query function (the hourglass icon)

**Comment by gpetit** [comment]
You are right. Thx. I will add it

**Comment by gpetit** [comment]
Included in the PR #21

**Comment by gpetit** [comment]
@nicolas-f done http://doc.orbisgis.org/en/latest/users/script_sql.html#sql-console

**Comment by nicolas-f** [comment]
@gpetit  Thanks
